#!/bin/bash
pdfseparate sertifikat2.pdf -f 1 -l 1 'M.  Fuhulur Rijal.pdf'
pdfseparate sertifikat2.pdf -f 2 -l 2 'Siti Nor khasanah.pdf'
pdfseparate sertifikat2.pdf -f 3 -l 3 'Yeni Aulia Rahmah.pdf'
pdfseparate sertifikat2.pdf -f 4 -l 4 'Imelda Ratnasari.pdf'
pdfseparate sertifikat2.pdf -f 5 -l 5 'Lia Rahmawati.pdf'
pdfseparate sertifikat2.pdf -f 6 -l 6 'Eka Marwana.pdf'
pdfseparate sertifikat2.pdf -f 7 -l 7 'Rizqa Karima.pdf'
pdfseparate sertifikat2.pdf -f 8 -l 8 'Restiana Utami.pdf'
pdfseparate sertifikat2.pdf -f 9 -l 9 'Muhammad Zaki.pdf'
pdfseparate sertifikat2.pdf -f 10 -l 10 'Nurhawa Rahmawati.pdf'
pdfseparate sertifikat2.pdf -f 11 -l 11 'Yulianti.pdf'
pdfseparate sertifikat2.pdf -f 12 -l 12 'Aulia Nur Yasmin.pdf'
pdfseparate sertifikat2.pdf -f 13 -l 13 'Muhammad Faridh.pdf'
pdfseparate sertifikat2.pdf -f 14 -l 14 'Muthia Ramadana.pdf'
pdfseparate sertifikat2.pdf -f 15 -l 15 'Lisa.pdf'
pdfseparate sertifikat2.pdf -f 16 -l 16 'Ludia Limbong Tasik.pdf'
pdfseparate sertifikat2.pdf -f 17 -l 17 'Yuliani.pdf'
pdfseparate sertifikat2.pdf -f 18 -l 18 'Rizalul Fikri.pdf'
pdfseparate sertifikat2.pdf -f 19 -l 19 'Ratu Olyvia Fadillah Putri.pdf'
pdfseparate sertifikat2.pdf -f 20 -l 20 'Hawa Putri Sellyana.pdf'
pdfseparate sertifikat2.pdf -f 21 -l 21 'Asih Meilani Putri.pdf'
pdfseparate sertifikat2.pdf -f 22 -l 22 'Susanti Ernawati .pdf'
pdfseparate sertifikat2.pdf -f 23 -l 23 'Ine Sentia.pdf'
pdfseparate sertifikat2.pdf -f 24 -l 24 'Dwi Anggrainy.pdf'
pdfseparate sertifikat2.pdf -f 25 -l 25 'Andina Cantika Muslimah.pdf'
pdfseparate sertifikat2.pdf -f 26 -l 26 'Dea amalia.pdf'
pdfseparate sertifikat2.pdf -f 27 -l 27 'Nadia Intania.pdf'
pdfseparate sertifikat2.pdf -f 28 -l 28 'Rizka Zulfia Mursyida.pdf'
pdfseparate sertifikat2.pdf -f 29 -l 29 'Sesilia Nathania Wahyudi.pdf'
pdfseparate sertifikat2.pdf -f 30 -l 30 'Devy Nurul Fitriani.pdf'
pdfseparate sertifikat2.pdf -f 31 -l 31 'Tasya Mahdalena.pdf'
pdfseparate sertifikat2.pdf -f 32 -l 32 'Muhammad Hifni.pdf'
pdfseparate sertifikat2.pdf -f 33 -l 33 'Riskita Aprila Putri.pdf'
pdfseparate sertifikat2.pdf -f 34 -l 34 'Puji Hayati.pdf'
pdfseparate sertifikat2.pdf -f 35 -l 35 'Afifah Afra Salsa Bila.pdf'
pdfseparate sertifikat2.pdf -f 36 -l 36 'Nazlatul Ashfiya.pdf'
pdfseparate sertifikat2.pdf -f 37 -l 37 'Ahmad Gunawan.pdf'
pdfseparate sertifikat2.pdf -f 38 -l 38 'Aisyah Nurmalina.pdf'
pdfseparate sertifikat2.pdf -f 39 -l 39 'Veronika Natalia Jeje.pdf'
pdfseparate sertifikat2.pdf -f 40 -l 40 'Handy kien Setiyawan.pdf'
pdfseparate sertifikat2.pdf -f 41 -l 41 'Elmayya Jihan Aulia.pdf'
pdfseparate sertifikat2.pdf -f 42 -l 42 'Deti Ernida.pdf'
pdfseparate sertifikat2.pdf -f 43 -l 43 'Noor Safnah.pdf'
pdfseparate sertifikat2.pdf -f 44 -l 44 'M. Hamdani.pdf'
pdfseparate sertifikat2.pdf -f 45 -l 45 'M. Yassin Nazar.pdf'
pdfseparate sertifikat2.pdf -f 46 -l 46 'Muhammad Faisal.pdf'
pdfseparate sertifikat2.pdf -f 47 -l 47 'Muhammad Hafi Bintang Rajabi.pdf'
pdfseparate sertifikat2.pdf -f 48 -l 48 'Muhammad Ahsanu Amali.pdf'
pdfseparate sertifikat2.pdf -f 49 -l 49 'Muhammad Didi Aditya Putra.pdf'
pdfseparate sertifikat2.pdf -f 50 -l 50 'Krisna Arka Gemilang.pdf'
pdfseparate sertifikat2.pdf -f 51 -l 51 'Adhitia Karisiyanto.pdf'
pdfseparate sertifikat2.pdf -f 52 -l 52 'Derry Sujatmiko.pdf'
pdfseparate sertifikat2.pdf -f 53 -l 53 'Suwandi.pdf'
pdfseparate sertifikat2.pdf -f 54 -l 54 'Merry Tallo Rara.pdf'
pdfseparate sertifikat2.pdf -f 55 -l 55 'Suci Lestari.pdf'
pdfseparate sertifikat2.pdf -f 56 -l 56 'Muhammad Atho.pdf'
pdfseparate sertifikat2.pdf -f 57 -l 57 'Gusti Yantoro.pdf'
pdfseparate sertifikat2.pdf -f 58 -l 58 'Rasminah.pdf'
pdfseparate sertifikat2.pdf -f 59 -l 59 'Aditya Hansarentino.pdf'
pdfseparate sertifikat2.pdf -f 60 -l 60 'Rositah.pdf'
pdfseparate sertifikat2.pdf -f 61 -l 61 'Noor Azizah.pdf'
pdfseparate sertifikat2.pdf -f 62 -l 62 'Nazwa Shada.pdf'
pdfseparate sertifikat2.pdf -f 63 -l 63 'Rahmadaniati.pdf'
pdfseparate sertifikat2.pdf -f 64 -l 64 'Rizky El Syafa.pdf'
pdfseparate sertifikat2.pdf -f 65 -l 65 'Lailatul Jannah.pdf'