#!/bin/bash
pdfseparate sertifikat.pdf -f 1 -l 1 'Azkia.pdf'
pdfseparate sertifikat.pdf -f 2 -l 2 'Adilia Putri.pdf'
pdfseparate sertifikat.pdf -f 3 -l 3 'Lathifah.pdf'
pdfseparate sertifikat.pdf -f 4 -l 4 'Firdha Aura Nabila.pdf'
pdfseparate sertifikat.pdf -f 5 -l 5 'Mulia Agustina.pdf'
pdfseparate sertifikat.pdf -f 6 -l 6 'Dayang Septia Pramesti.pdf'
pdfseparate sertifikat.pdf -f 7 -l 7 'DESTI ADHE LIANDRA.pdf'
pdfseparate sertifikat.pdf -f 8 -l 8 'Maulida Rahma.pdf'
pdfseparate sertifikat.pdf -f 9 -l 9 'MULIA UMRAH.pdf'
pdfseparate sertifikat.pdf -f 10 -l 10 'Tansa Aliza Aprila.pdf'
pdfseparate sertifikat.pdf -f 11 -l 11 'Friska Arlina.pdf'
pdfseparate sertifikat.pdf -f 12 -l 12 'Ahmad Saman Almadani .pdf'
pdfseparate sertifikat.pdf -f 13 -l 13 'Nabilla.pdf'
pdfseparate sertifikat.pdf -f 14 -l 14 'Rabiatul Adawiah .pdf'
pdfseparate sertifikat.pdf -f 15 -l 15 'Nurul Husna.pdf'
pdfseparate sertifikat.pdf -f 16 -l 16 'Aminatuzzuhriyah.pdf'
pdfseparate sertifikat.pdf -f 17 -l 17 'Nur Jannah.pdf'
pdfseparate sertifikat.pdf -f 18 -l 18 'Siti Zahra Setiani.pdf'
pdfseparate sertifikat.pdf -f 19 -l 19 'Latifah Dwi Yanti.pdf'
pdfseparate sertifikat.pdf -f 20 -l 20 'Nur Indah Dewi Pratiwi.pdf'
pdfseparate sertifikat.pdf -f 21 -l 21 'Nurhasanah Putri.pdf'
pdfseparate sertifikat.pdf -f 22 -l 22 'Amazia Josevan.pdf'
pdfseparate sertifikat.pdf -f 23 -l 23 'Dhea Febryanti.pdf'
pdfseparate sertifikat.pdf -f 24 -l 24 'Dwi Anggrainy.pdf'
pdfseparate sertifikat.pdf -f 25 -l 25 'Nurlatifah.pdf'
pdfseparate sertifikat.pdf -f 26 -l 26 'Mariatul Kiptiah.pdf'
pdfseparate sertifikat.pdf -f 27 -l 27 'Norma Waddah.pdf'
pdfseparate sertifikat.pdf -f 28 -l 28 'Khairunnisa.pdf'
pdfseparate sertifikat.pdf -f 29 -l 29 'Ardelitha Aliyah.pdf'
pdfseparate sertifikat.pdf -f 30 -l 30 'Siti Amelia Putri.pdf'
pdfseparate sertifikat.pdf -f 31 -l 31 'OCTAVIANOR SYA’BANIA.pdf'
pdfseparate sertifikat.pdf -f 32 -l 32 'Rahma Azkiya.pdf'
pdfseparate sertifikat.pdf -f 33 -l 33 'Intan Nur Aziza.pdf'
pdfseparate sertifikat.pdf -f 34 -l 34 'Nazua Salsabila.pdf'
pdfseparate sertifikat.pdf -f 35 -l 35 'Ni Made Oktavia Ariyani.pdf'
pdfseparate sertifikat.pdf -f 36 -l 36 'Fery Alexanderia .pdf'
pdfseparate sertifikat.pdf -f 37 -l 37 'MUHAMMAD ISRO.pdf'
pdfseparate sertifikat.pdf -f 38 -l 38 'Siti Humairah .pdf'
pdfseparate sertifikat.pdf -f 39 -l 39 'Naimah .pdf'
pdfseparate sertifikat.pdf -f 40 -l 40 'Niken Fajeriah.pdf'
pdfseparate sertifikat.pdf -f 41 -l 41 'Ikhsan Marifaturrahman.pdf'
pdfseparate sertifikat.pdf -f 42 -l 42 'eldisina.pdf'
pdfseparate sertifikat.pdf -f 43 -l 43 'Adit Muhammad .pdf'
pdfseparate sertifikat.pdf -f 44 -l 44 'Aina Syifa.pdf'
pdfseparate sertifikat.pdf -f 45 -l 45 'M.Samli.pdf'
pdfseparate sertifikat.pdf -f 46 -l 46 'Reza kartika dewi.pdf'
pdfseparate sertifikat.pdf -f 47 -l 47 'Siti Nur Hafsah.pdf'
pdfseparate sertifikat.pdf -f 48 -l 48 'Azhar Noor Ayubban .pdf'
pdfseparate sertifikat.pdf -f 49 -l 49 'Muhammad ikhsan .pdf'
pdfseparate sertifikat.pdf -f 50 -l 50 'Muhammad ibnu mulia.pdf'
pdfseparate sertifikat.pdf -f 51 -l 51 'Naiya Mardatillah .pdf'
pdfseparate sertifikat.pdf -f 52 -l 52 'Maimunah.pdf'
pdfseparate sertifikat.pdf -f 53 -l 53 'Mitha Audina.pdf'
pdfseparate sertifikat.pdf -f 54 -l 54 'Dendy Adi Saputra.pdf'
pdfseparate sertifikat.pdf -f 55 -l 55 'GUSTI BULAN DAWILAH.pdf'
pdfseparate sertifikat.pdf -f 56 -l 56 'Juniarti adha rini.pdf'
pdfseparate sertifikat.pdf -f 57 -l 57 'Noorsyipa.pdf'
pdfseparate sertifikat.pdf -f 58 -l 58 'Gusti Naura Salsabila.pdf'
pdfseparate sertifikat.pdf -f 59 -l 59 'Rizka Amalia.pdf'
pdfseparate sertifikat.pdf -f 60 -l 60 'Norlatifah.pdf'
pdfseparate sertifikat.pdf -f 61 -l 61 'Putri Az-Zahra.pdf'
pdfseparate sertifikat.pdf -f 62 -l 62 'Rismawati.pdf'
pdfseparate sertifikat.pdf -f 63 -l 63 'Nur Sari Fahriana.pdf'
pdfseparate sertifikat.pdf -f 64 -l 64 'Nasywaa Asy Syifa.pdf'
pdfseparate sertifikat.pdf -f 65 -l 65 'Hafsah Noor Muthmainnah.pdf'
pdfseparate sertifikat.pdf -f 66 -l 66 'Arvina Rafika Puteri.pdf'
pdfseparate sertifikat.pdf -f 67 -l 67 'Elisa Sintani .pdf'
pdfseparate sertifikat.pdf -f 68 -l 68 'Febi Charisma Putri.pdf'
pdfseparate sertifikat.pdf -f 69 -l 69 'Mcoh Rayhanoor Adam S.pdf'
pdfseparate sertifikat.pdf -f 70 -l 70 'YENI NISRINA .pdf'
pdfseparate sertifikat.pdf -f 71 -l 71 'amanah niah.pdf'
pdfseparate sertifikat.pdf -f 72 -l 72 'Nur Syifa Kavinahua .pdf'
pdfseparate sertifikat.pdf -f 73 -l 73 'Widya nur safitri.pdf'
pdfseparate sertifikat.pdf -f 74 -l 74 'Nurussyifa Zaenaliza.pdf'
pdfseparate sertifikat.pdf -f 75 -l 75 'DEWI SUSI LISTIANI.pdf'
pdfseparate sertifikat.pdf -f 76 -l 76 'Meka Defina Fitra .pdf'
pdfseparate sertifikat.pdf -f 77 -l 77 'Anjar pribadi.pdf'
pdfseparate sertifikat.pdf -f 78 -l 78 'M. Sadik.pdf'
pdfseparate sertifikat.pdf -f 79 -l 79 'lisa.pdf'
pdfseparate sertifikat.pdf -f 80 -l 80 'Putri Ervina Ulfah .pdf'
pdfseparate sertifikat.pdf -f 81 -l 81 'Dwi Dirga Apriliana.pdf'
pdfseparate sertifikat.pdf -f 82 -l 82 'Ronny Aryo Pratomo.pdf'
pdfseparate sertifikat.pdf -f 83 -l 83 'Eka Puspita Br Sirait .pdf'
pdfseparate sertifikat.pdf -f 84 -l 84 'Alfita Nur Khalisah.pdf'
pdfseparate sertifikat.pdf -f 85 -l 85 'Maghfirah.pdf'
pdfseparate sertifikat.pdf -f 86 -l 86 'Annisa Fitria Humairoh.pdf'
pdfseparate sertifikat.pdf -f 87 -l 87 'Marlianda.pdf'
pdfseparate sertifikat.pdf -f 88 -l 88 'Khairatunnisa.pdf'
pdfseparate sertifikat.pdf -f 89 -l 89 'Laila.pdf'
pdfseparate sertifikat.pdf -f 90 -l 90 'Rizkyan Noor Ramanda.pdf'
pdfseparate sertifikat.pdf -f 91 -l 91 'Adi Ibanez Zidane.pdf'
pdfseparate sertifikat.pdf -f 92 -l 92 'Nabilla.pdf'
pdfseparate sertifikat.pdf -f 93 -l 93 'Gusti Salsabila Fitriani .pdf'
pdfseparate sertifikat.pdf -f 94 -l 94 'Ani fitrianti.pdf'
pdfseparate sertifikat.pdf -f 95 -l 95 'Ners. Husin, S.Kep., MPH..pdf'
pdfseparate sertifikat.pdf -f 96 -l 96 'Nirma Yunita, S.Si.T., M.M..pdf'
pdfseparate sertifikat.pdf -f 97 -l 97 'Eka Rahma Ningsih, S.KM., M.Kes..pdf'
pdfseparate sertifikat.pdf -f 98 -l 98 'Fadhliah, A.Md.Kes., S.KM..pdf'
pdfseparate sertifikat.pdf -f 99 -l 99 'Muhammad Rashif Anshari, S.H., M.H..pdf'
pdfseparate sertifikat.pdf -f 100 -l 100 'Saipi, S.Kom.pdf'
pdfseparate sertifikat.pdf -f 101 -l 101 'Soraya, A.Md.RMIK,SKM.,M.Kes.pdf'
